import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({
  fetchSubtitlesWithYtDlp: vi.fn(),
  fetchTranscriptWithYtDlp: vi.fn(async () => ({
    text: "transcribed audio",
    provider: "groq" as const,
    error: null,
    notes: [],
  })),
  fetchDurationSecondsWithYtDlp: vi.fn(async () => null),
}));

vi.mock("../src/core/content/transcript/providers/youtube/yt-dlp-subs.js", () => ({
  fetchSubtitlesWithYtDlp: mocks.fetchSubtitlesWithYtDlp,
}));

vi.mock("../src/core/content/transcript/providers/youtube/yt-dlp.js", () => ({
  fetchTranscriptWithYtDlp: mocks.fetchTranscriptWithYtDlp,
  fetchDurationSecondsWithYtDlp: mocks.fetchDurationSecondsWithYtDlp,
}));

import { fetchTranscript } from "../src/core/content/transcript/providers/youtube.js";

const VIDEO_URL = "https://www.youtube.com/watch?v=-RXD4bTuFTo";
// A watch page that bootstraps but exposes no caption tracks — what YouTube now serves
// anonymous requests, and the reason the youtubei/captionTracks rungs come up empty.
const HTML_WITHOUT_CAPTIONS =
  '<html><script>ytInitialPlayerResponse = {"videoDetails":{}}</script></html>';

const baseOptions = {
  fetch: vi.fn(async () => new Response("", { status: 404 })) as unknown as typeof fetch,
  scrapeWithFirecrawl: null as unknown as ((...args: unknown[]) => unknown) | null,
  apifyApiToken: null,
  youtubeTranscriptMode: "auto" as const,
  mediaTranscriptMode: "auto" as const,
  ytDlpPath: "/usr/local/bin/yt-dlp",
  groqApiKey: "GROQ",
  onProgress: null,
};

describe("youtube provider - yt-dlp subtitle rung", () => {
  beforeEach(() => {
    mocks.fetchSubtitlesWithYtDlp.mockReset();
    mocks.fetchTranscriptWithYtDlp.mockClear();
  });

  it("uses yt-dlp subtitles instead of downloading audio when the page has no caption tracks", async () => {
    mocks.fetchSubtitlesWithYtDlp.mockResolvedValue({
      payload: { text: "hello from subtitles", segments: null },
      kind: "manual",
      error: null,
      notes: [],
    });

    const result = await fetchTranscript(
      { url: VIDEO_URL, html: HTML_WITHOUT_CAPTIONS, resourceKey: "-RXD4bTuFTo" },
      baseOptions,
    );

    expect(result.source).toBe("yt-dlp-subs");
    expect(result.text).toBe("hello from subtitles");
    expect(result.metadata?.subtitleKind).toBe("manual");
    expect(result.attemptedProviders).toContain("yt-dlp-subs");
    expect(mocks.fetchTranscriptWithYtDlp).not.toHaveBeenCalled();
  });

  it("falls through to audio transcription when no subtitles exist", async () => {
    mocks.fetchSubtitlesWithYtDlp.mockResolvedValue({
      payload: null,
      kind: null,
      error: null,
      notes: ["yt-dlp found no manual subtitles"],
    });

    const result = await fetchTranscript(
      { url: VIDEO_URL, html: HTML_WITHOUT_CAPTIONS, resourceKey: "-RXD4bTuFTo" },
      baseOptions,
    );

    expect(result.source).toBe("yt-dlp");
    expect(result.text).toBe("transcribed audio");
    expect(mocks.fetchTranscriptWithYtDlp).toHaveBeenCalledTimes(1);
  });

  it("skips auto-generated subtitles in no-auto mode", async () => {
    mocks.fetchSubtitlesWithYtDlp.mockResolvedValue({
      payload: { text: "creator captions", segments: null },
      kind: "manual",
      error: null,
      notes: [],
    });

    const result = await fetchTranscript(
      { url: VIDEO_URL, html: HTML_WITHOUT_CAPTIONS, resourceKey: "-RXD4bTuFTo" },
      { ...baseOptions, youtubeTranscriptMode: "no-auto" as const },
    );

    expect(result.source).toBe("yt-dlp-subs");
    expect(mocks.fetchSubtitlesWithYtDlp).toHaveBeenCalledWith(
      expect.objectContaining({ skipAutoGenerated: true }),
    );
  });
});
