import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnTracked } from "../../../../processes.js";
import type { TranscriptPayload } from "./captions-shared.js";
import { parseJsonTranscript } from "./captions-transcript.js";

const SUBTITLE_TIMEOUT_MS = 90_000;
const MAX_STDERR_BYTES = 8192;

// Manual (creator) tracks are requested in full rather than filtered to the languages we
// rank: a non-English video's only creator track is its own language, and narrowing to
// `en` would skip it in favour of a machine translation. The cost is bounded by the
// timeout below — a channel with dozens of translated tracks downloads all of them.
// Auto-captions cannot be requested that way: YouTube offers the machine translation of
// an auto-track into every language it knows, so `all` would pull hundreds of files.
// `.*-orig` is the original spoken language, the only auto-track that isn't a translation.
const MANUAL_SUB_LANGS = "all,-live_chat";
const AUTO_SUB_LANGS = ".*-orig,en";

export type SubtitleKind = "manual" | "auto";

export type YtDlpSubtitleResult = {
  payload: TranscriptPayload | null;
  kind: SubtitleKind | null;
  error: Error | null;
  notes: string[];
};

/**
 * Read a YouTube transcript from yt-dlp's subtitle endpoints instead of the watch page.
 *
 * The watch-page HTML no longer carries `captionTracks` for anonymous requests, so the
 * youtubei/captionTracks rungs come up empty even for videos that do have captions.
 * yt-dlp reaches the same tracks through the player API. This costs a few hundred KB of
 * JSON rather than a full audio download plus paid transcription, and it survives the
 * HTTP 403 that YouTube returns for media fetches from server IPs without a PO token.
 */
export const fetchSubtitlesWithYtDlp = async ({
  ytDlpPath,
  url,
  skipAutoGenerated = false,
}: {
  ytDlpPath: string | null;
  url: string;
  skipAutoGenerated?: boolean;
}): Promise<YtDlpSubtitleResult> => {
  const notes: string[] = [];
  if (!ytDlpPath) {
    return { payload: null, kind: null, error: null, notes };
  }

  const workDir = await fs.mkdtemp(join(tmpdir(), "summarize-subs-"));
  try {
    const attempts: SubtitleKind[] = skipAutoGenerated ? ["manual"] : ["manual", "auto"];
    for (const kind of attempts) {
      const outputTemplate = join(workDir, kind);
      try {
        await runYtDlpSubtitles(ytDlpPath, url, outputTemplate, kind);
      } catch (error) {
        notes.push(`yt-dlp ${kind} subtitles failed: ${describeError(error)}`);
        continue;
      }

      const payload = await readBestSubtitleFile(workDir, kind);
      if (payload) {
        return { payload, kind, error: null, notes };
      }
      notes.push(`yt-dlp found no ${kind} subtitles`);
    }

    return { payload: null, kind: null, error: null, notes };
  } catch (error) {
    return {
      payload: null,
      kind: null,
      error: error instanceof Error ? error : new Error(String(error)),
      notes,
    };
  } finally {
    await fs.rm(workDir, { recursive: true, force: true }).catch(() => {});
  }
};

function runYtDlpSubtitles(
  ytDlpPath: string,
  url: string,
  outputTemplate: string,
  kind: SubtitleKind,
): Promise<void> {
  return new Promise((resolve, reject) => {
    const args = [
      "--skip-download",
      kind === "manual" ? "--write-subs" : "--write-auto-subs",
      "--sub-langs",
      kind === "manual" ? MANUAL_SUB_LANGS : AUTO_SUB_LANGS,
      "--sub-format",
      "json3",
      "--no-playlist",
      "--no-warnings",
      "-o",
      outputTemplate,
      url,
    ];

    const { proc } = spawnTracked(ytDlpPath, args, {
      stdio: ["ignore", "ignore", "pipe"],
      label: "yt-dlp",
      kind: "yt-dlp",
    });
    let stderr = "";

    if (proc.stderr) {
      proc.stderr.setEncoding("utf8");
      proc.stderr.on("data", (chunk: string) => {
        if (stderr.length < MAX_STDERR_BYTES) {
          stderr += chunk.slice(0, MAX_STDERR_BYTES - stderr.length);
        }
      });
    }

    const timeout = setTimeout(() => {
      proc.kill("SIGTERM");
      reject(new Error("yt-dlp subtitle timeout"));
    }, SUBTITLE_TIMEOUT_MS);

    proc.on("close", (code, signal) => {
      clearTimeout(timeout);
      if (code === 0) {
        resolve();
        return;
      }
      const detail = stderr.trim();
      const suffix = detail ? `: ${detail}` : "";
      if (code === null) {
        reject(new Error(`yt-dlp terminated (${signal ?? "unknown"})${suffix}`));
        return;
      }
      reject(new Error(`yt-dlp exited with code ${code}${suffix}`));
    });

    proc.on("error", (error) => {
      clearTimeout(timeout);
      reject(error);
    });
  });
}

/**
 * yt-dlp writes one file per matched language (`<kind>.<lang>.json3`). Rank them so the
 * choice is deterministic: English first (matching the captionTracks rung's preference),
 * then the original spoken language, then whatever else arrived.
 */
async function readBestSubtitleFile(
  workDir: string,
  kind: SubtitleKind,
): Promise<TranscriptPayload | null> {
  const entries = await fs.readdir(workDir).catch(() => [] as string[]);
  const candidates = entries
    .filter((entry) => entry.startsWith(`${kind}.`) && entry.endsWith(".json3"))
    .toSorted((a, b) => rankSubtitleFile(a) - rankSubtitleFile(b));

  for (const candidate of candidates) {
    const raw = await fs.readFile(join(workDir, candidate), "utf8").catch(() => null);
    if (!raw) continue;
    const payload = parseJsonTranscript(raw);
    if (payload) return payload;
  }
  return null;
}

function rankSubtitleFile(filename: string): number {
  const lang = filename.replace(/^[^.]+\./, "").replace(/\.json3$/, "");
  if (lang === "en") return 0;
  if (lang.endsWith("-orig")) return 1;
  if (lang.startsWith("en")) return 2;
  return 3;
}

function describeError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
